name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v6
        with:
            path: |
              .cpcache
              .shadow-cljs
              ~/.m2
            key: "1"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.7.0
        with:
          cli: latest
          bb: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build static site
        run: bb build-static

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/build
